#!/bin/bash

T="0"
REFRESCO="5"
date +"%H:%M:%S"
sleep $REFRESCO
clear

while true
do
T=$(echo $((5 + $T)))
date +"%H:%M:%S"
echo "La tarea lleva $T seg"
echo "$T" > ~/.config/log.tiempo
sleep $REFRESCO
clear
done
