#!/bin/bash

T="0"
REFRESCO="60"
date +"%H:%M:%S"
sleep $REFRESCO
clear

while true
do
T=$(echo $((1 + $T)))
date +"%H:%M:%S"
echo "$T" > ~/.config/log.tiempo
sleep $REFRESCO
clear
echo "La tarea $(cat ~/.config/task.tiempo) lleva $T min"
done
