#!/bin/bash                      
VERSION="v0.1.4 14/09/2020"

ARCHIVO_TODO="/home/angel/todo/todo.txt"
ARCHIVO_DONE="/home/angel/todo/done.txt"
SCRIPT_PATH="$HOME/ttodo"


TOPYDO="topydo -t "$ARCHIVO_TODO" -d "$ARCHIVO_DONE""
TOPYDOP="topydo -t "$ARCHIVO_TODO" -d "$ARCHIVO_DONE" prompt"
TOPYDOC="topydo -t "$ARCHIVO_TODO" -d "$ARCHIVO_DONE" columns"
TODOTXT_MACHINE="todotxt-machine "$ARCHIVO_TODO" "$ARCHIVO_DONE""
TODOTXTCLI="todo-txt"


if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "h" ]
then
echo " 
todo.txt en uno. topydo + todotxt-machine + control de tiempo

Modo de empleo: ttodo [OPCIONES]    
t -t             Inicio de todotxt-cli 
t -p             Inicio de topydo prompt           
t -c             Inicio de topydo columns
t -m             Inicio de todotxt-machine
t  t  nº_tarea   Iniciar contador
t  r  nº_tarea   Resumen del tiempo empleado en una tarea
t -i             Instalar todas las app's para versiones debian y derivadas 

ttodo "$VERSION"
Copyright (C) 2020 Angel. uGeek                                                                                                                                                                                  
 ugeekpodcast@gmail.com"




exit
fi


if [ "$1" = "-i" ]
then
   sudo pip3 install todotxt-machine
   sudo pip3 install topydo
   sudo pip3 install 'topydo[columns]'
   sudo pip3 install "topydo[prompt]"
   sudo apt install todotxt-cli apcalc screen
   echo ""
   echo "¿Cual es el nombre de usuario donde quieres instalar todotxt-cli?" ; read USUARIO
   mkdir -p /home/$USUARIO/.todo
   echo "export TODO_DIR="'"'"$(echo $ARCHIVO_TODO | sed 's|todo.txt||'g)"'"'"" > /home/$USUARIO/.todo/config
   echo "export TODO_FILE="'"$TODO_DIR/todo.txt"'"" >> /home/$USUARIO/.todo/config
   echo "export DONE_FILE="'"$TODO_DIR/done.txt"'"" >> /home/$USUARIO/.todo/config
   echo "export REPORT_FILE="'"$TODO_DIR/report.txt"'"" >> /home/$USUARIO/.todo/config 
   echo "export TMP_FILE="'"/tmp/todo.tmp"'"" >> /home/$USUARIO/.todo/config
   echo "export TODOTXT_DEFAULT_ACTION=ls" >> /home/$USUARIO/.todo/config   
   exit
fi

if [ "$1" = "t" ]
then
echo ""
cat  $ARCHIVO_TODO | sed -n "$2"p > ~/.config/task.tiempo

sed "$2d" $ARCHIVO_TODO  > $ARCHIVO_TODO.b

echo "0" > ~/.config/log.tiempo

sed -i "$2d" $ARCHIVO_TODO

screen -dmS ttodot $SCRIPT_PATH/ttodot
screen -dmS ttodonf $SCRIPT_PATH/ttodonf

clear
echo "Contabilizando el tiempo de la tarea:" 
echo ""
echo "  - $( cat ~/.config/task.tiempo)"
echo ""
echo "  Pulsa una tecla para detener el contandor" ; read STOCK

TIME=$(cat ~/.config/log.tiempo)
echo "$(cat ~/.config/task.tiempo) time:"$TIME":$(date +"%Y%m%d:%T")" >> $ARCHIVO_TODO.b
cp $ARCHIVO_TODO.b $ARCHIVO_TODO

clear
echo ""
echo "Tiempo: $(cat ~/.config/log.tiempo)"
echo ""
echo "Tarea : $(cat $ARCHIVO_TODO | tail -1)"
echo ""
screen -XS ttodot quit
screen -XS ttodonf quit
exit
fi

if [ "$1" = "r" ]
then
clear
MIN=$(cat  $ARCHIVO_TODO | sed -n "$2"p |  tr -s '[:blank:]' '\n' | grep "time:" | cut -d ":" -f2 | paste -sd+ - | bc )

echo ""
echo "Tarea: "
echo "---------------------"
echo "$(cat  $ARCHIVO_TODO | sed -n "$2"p)"
echo ""
echo ""
echo "Tiempo total: $(printf '%dh:%dm\n' $(($MIN/60)) $(($MIN%60/1)))"
echo "---------------------"
echo "Resumen de tiempos:"
cat $ARCHIVO_TODO | sed -n "$2"p |  tr -s '[:blank:]' '\n' | grep "time:" | cut -d ":" -f2 | sed 's/$/ min/' | sed 's/^/- /'
echo ""
echo "Dias de los registros de tiempo:"
echo "--------------------------------"
cat $ARCHIVO_TODO  | sed -n "$2"p |  tr -s '[:blank:]' '\n' | grep "time:" | cut -d ":" -f3 | column| sed s'|\t|,|'g
echo ""
exit
fi

if [ "$1" = "-p" ]
then
$TOPYDOP
exit
fi

if [ "$1" = "-c" ]
then
$TOPYDOC
exit
fi

if [ "$1" = "-m" ]
then
$TODOTXT_MACHINE    
exit
fi

if [ "$1" = "-t" ]
then
$TODOTXTCLI    
exit
fi

if [ "$1" = "-i" ]
then
    sudo pip3 install topydo
    sudo pip3 install "topydo[prompt]"
    sudo pip3 install 'topydo[columns]'
    sudo apt install todotxt-cli screen bc
    sudo pip3 install todotxt-machine
    sudo chmod +x *
exit
fi

$TOPYDO $*

